name: "nyk_ngayogyan_jejeg"
designer: "Apri Nugroho, Arif Budiarto"
license: "OFL"
category: "SANS_SERIF"
date_added: "2020-07-22"
fonts {
  name: "nyk_ngayogyan_jejeg"
  style: "normal"
  weight: 300
  filename: "nyk_ngayogyan_jejeg.ttf"
  post_script_name: "nyk_ngayogyan_jejeg"
  full_name: "nyk_ngayogyan_jejeg"
  copyright: "Copyright 2020 The nyk_ngayogyan_jejeg Project Authors (https://github.com/)"
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "hebrew"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
